version: "3.6"
#IMPORTANTE: Você terá 1.5 CPUs e 3.0GB
services:
  cache:
    image: quay.io/infinispan/server-native:14.0.13.Final-1
    ports:
      - "11222:11222"
    environment:
      USER: quarkus
      PASS: quarkus
    deploy:
      resources:
        limits:
          cpus: '0.2'
          memory: '0.2GB'
  api1:
    image: quarkus/quarkus-app-imperativo-jvm
    environment:
      DB_HOST: db
      QUARKUS_LOG_CONSOLE_ENABLE: true
      QUARKUS_LOG_FILE_ENABLE: false
    depends_on:
      - db
      - cache
    deploy:
      resources:
        limits:
          cpus: '0.4'
          memory: '0.5GB'
    ulimits:
      nproc: 65535
      nofile:
        soft: 20000
        hard: 40000

  api2:
    image: quarkus/quarkus-app-imperativo-jvm
    environment:
      DB_HOST: db
      QUARKUS_LOG_CONSOLE_ENABLE: true
      QUARKUS_LOG_FILE_ENABLE: false
    depends_on:
      - db
      - cache
    deploy:
      resources:
        limits:
          cpus: '0.4'
          memory: '0.5GB'
    ulimits:
      nproc: 65535
      nofile:
        soft: 20000
        hard: 40000

  nginx:
    image: nginx:1.25.1
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - api1
      - api2
    ports:
      - "9999:9999"
    deploy:
      resources:
        limits:
          cpus: '0.2'
          memory: '0.2GB'

  db:
    image: postgres:15.4
    command: postgres -c 'max_connections=400'
    volumes:
      - ../db:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: quarkus
      POSTGRES_PASSWORD: quarkus
      POSTGRES_DB: quarkus
    deploy:
      resources:
        limits:
          cpus: '0.3'
          memory: '2.0GB'